### ISSUE TITLE
学习学习

### ISSUE THREAD

**Issue by JUNJIEDREAM** [zhengguanji/hpyfoo#1]
小白想参考学习一下，自己运行在电脑上，发现没有具体的Installation和run方法呀，能不能补充一下，拜托啦，非常感谢~~！！

**Comment by zhengguanji** [comment]
你要先新建一个虚拟环境：
```virtualenv 虚拟环境名字```
虚拟环境名字你可以随便起，例如叫`venv`，那你就运行`virtualenv venv`，如果要指定Python版本，那就这样
`virtualenv -p /path/python.exe venv`
`path`换成你的Python安装目录，安装好虚拟环境你再运行
`pip install -r requirements.txt`
这个命令是用来安装这个项目需要的包的，安装好之后，你再执行`虚拟环境名字/scripts/activate`激活虚拟环境，然后就可以运行项目了
