### ISSUE TITLE
pip install -r requirements.txt 失败

### ISSUE THREAD

**Issue by JUNJIEDREAM** [zhengguanji/hpyfoo#2]
在安装misaka时报错，具体：
Collecting misaka==2.1.0 (from -r requirements.txt (line 25))
  Downloading misaka-2.1.0.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 424kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
     File "<string>", line 1, in <module>
      File "c:\users\92457\appdata\local\temp\pip-build-h7qezs\misaka\setup.py", line 76, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "C:\Python27\Lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
**********************************************************************************
 ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\92457\appdata\local\temp\pip-build-h7qezs\misaka\

**Comment by zhengguanji** [comment]
我那个时候好像也碰到了这个错误，后来好像是安装了`cffi`跟`libffi-dev`才解决的，参考这里：
https://github.com/FSX/misaka/issues/51
